Out-oforder lsu
pulp-platform/mempool pull request #13
Opened 2021-08-10 13:09 UTC by khovg

Summarize the changes concisely

## Changelog

### Added

### Changed

### Fixed

(Reference to issues, labels, and related merge requests)

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2021-08-10 13:15 UTC, suehtamacv requested changes
Looks good, Gua Hao! I have a few comments about your PR.

2021-08-10 13:15 UTC, suehtamacv commented on hardware/deps/snitch/src/snitch_lsu.sv
> +  if (NumOutstandingLoads == 0) begin
Synopsys understands this construct. There is no need to put a `pragma translate_off` before this construct, since we actually want to check whether `NumOutstandingLoads == 0` during elaboration.

You can move this `pragma translate_off` guard to the SVA assertions.

2021-08-10 13:15 UTC, suehtamacv commented on hardware/src/mempool_tile.sv
> +  meta_id_t [NumCoresPerTile-1:0]    snitch_data_qid;
Vertical alignment.

2021-08-10 15:25 UTC, SamuelRiedel requested changes
Nice! I only have some minor nitpicks about alignment, and I will check why the Halide test fails.

2021-08-10 15:25 UTC, SamuelRiedel commented on hardware/src/mempool_tile.sv
> +        .tcdm_resp_id_i     ({local_resp_interco_payload[c].rdata.meta_id, remote_resp_interco[c].rdata.meta_id}      ),
You could delete the whitespaces to the right due to the new name

2021-08-13 12:33 UTC, SamuelRiedel commented
Please also add your changes to the [changelog](https://github.com/pulp-platform/mempool/blob/main/CHANGELOG.md) and your name to the [contributors](https://github.com/pulp-platform/mempool/blob/main/CONTRIBUTORS.md).

2021-08-17 07:30 UTC, suehtamacv commented
Please rebase your work on top of `main`, since @SamuelRiedel just merged #17, a fix to the I$ issue. Let us see whether that fix the CI of this PR.

2021-08-17 11:47 UTC, suehtamacv approved these changes
LGTM, thanks for the contribution! Please add your name to `CONTRIBUTORS.md` before merging this PR.

2021-08-17 11:49 UTC, SamuelRiedel reviewed
LGTM. One thing I didn't notice before: Now that we don't need the ROB anymore, can you please remove it from the repo and the Bender.yml?

2021-08-17 12:55 UTC, SamuelRiedel approved these changes
Perfect. Thanks a lot.

2021-08-17 12:56 UTC, merged