Add Stack overflow warning
pulp-platform/mempool pull request #64
Opened 2022-10-25 15:58 UTC by LucaRufer

## Changelog

### Added

Add simulator warning on stack overflow. Uses dedicated CSR holding the stack limit for every core

### Changed

rd bypass: split into control path and data path

### Fixed

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-10-31 11:40 UTC, SamuelRiedel requested changes
Looks good, thanks a lot. :+1: I have one small suggestion to reduce code duplication in the generate statements.

Also, I see why you changed the bypass logic, but since both versions' functionality and readability are the same, I would leave the code as is to avoid unnecessary changes. Can you please revert those modifications?

Finally, please rebase your work on the current `main` branch, and then this is ready to merge from my side.

2022-10-31 11:40 UTC, SamuelRiedel commented on hardware/deps/snitch/src/snitch.sv
> +  // pragma translate_on
This whole block could be in the `// pragma traslate_off` block since it's all just for the simulation warning. Even better, to make it generic for any number of write ports and a bit more compact, you could rewrite it like this.

```suggestion
  // pragma translate_off
  for (genvar i = 0; i < RegNrWritePorts; i++) begin : gen_stack_overflow_check
    logic [31:0] sp_new_value;
    assign sp_new_value = gpr_wdata[i];
    always_ff @(posedge clk_i or posedge rst_i) begin
      if (!rst_i && gpr_we[i] && gpr_waddr[i] == SP && csr_stack_limit_q != 32'hFFFF_FFFF && ($signed(sp_new_value) < $signed(csr_stack_limit_q))) begin
        $warning("[Stackoverflow: Core %0d] Set SP to 0x%08h, limit is 0x%08h", hart_id_i, sp_new_value, csr_stack_limit_q);
      end
    end
  end
  // pragma translate_on
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +  enum logic [1:0] {BypassNone, Uimm, CSRRvalue} rd_bypass_select;
```suggestion
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +    rd_bypass_select = BypassNone;
```suggestion
    rd_bypass = '0;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +        rd_bypass_select = Uimm;
```suggestion
        rd_bypass = uimm;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +        rd_bypass_select = CSRRvalue;
```suggestion
        rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +        rd_bypass_select = CSRRvalue;
```suggestion
        rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +          rd_bypass_select = CSRRvalue;
```suggestion
          rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +          rd_bypass_select = CSRRvalue;
```suggestion
          rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +        rd_bypass_select = CSRRvalue;
```suggestion
        rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +          rd_bypass_select = CSRRvalue;
```suggestion
          rd_bypass = csr_rvalue;
```

2022-10-31 13:25 UTC, LucaRufer commented on hardware/deps/snitch/src/snitch.sv
> +
```suggestion
```

2022-11-01 12:28 UTC, SamuelRiedel approved these changes
Looks good now. Thanks a lot :+1:

2022-11-01 12:29 UTC, merged