WIP: Add Hierarchical AXI cache
pulp-platform/mempool pull request #7
Opened 2021-07-16 02:58 UTC by SamuelRiedel

Add a read-only cache that has an AXI Master and Slave port and can be inserted into the AXI interconnect directly.

The cache is in an early stage and only works in specific configurations.

## Changelog

### Added
- Hierarchical AXI interconnect

### Changed

### Fixed

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

2022-01-28 08:28 UTC, suehtamacv requested changes

2022-01-28 08:28 UTC, suehtamacv commented on hardware/deps/snitch/src/snitch_icache/snitch_icache.sv
> +            .out_rsp_ready_o ( local_prefetch_rsp_ready  )
Vertical alignment.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/deps/snitch/src/snitch_icache/snitch_icache.sv
> +    input  axi_rsp_t axi_rsp_i
Vertical alignment.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/deps/snitch/src/snitch_icache/snitch_icache.sv
> -        .data_o  ( extern_rsp_q    )
Are those slices integrated with some other module?

2022-01-28 08:28 UTC, suehtamacv commented on hardware/deps/snitch/src/snitch_icache/snitch_icache_refill.sv
>          .DATA_WIDTH ( CFG.PENDING_IW+1 )
Vertical alignment.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/axi_hier_interco.sv
> +  end else if (Radix <= 1) begin : gen_error
This is equivalent to `if (Radix <= 1 && NumMstPorts < NumSlvPorts)`. Is this the condition you wanted, or could this error condition be moved to the beginning of the block?

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/axi_hier_interco.sv
> +    end
Maybe put the `generate for` in the else condition of the if.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/axi_hier_interco.sv
> +        .SetCount     (2           ),
Any reasoning behind those hardcoded parameters?

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/ctrl_registers.sv
> +  // [59:56]:ro_cache_end_3                 (rw)
Why four?

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/mempool_cluster.sv
> +      .NumAXIMasters(NumAXIMasters/NumGroups)
Vertical alignment. Also, you can use your `NumAxiMastersPerGroup` parameter.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/mempool_pkg.sv
> +  localparam integer unsigned AxiDataWidth     = `ifdef AXI_WIDTH `AXI_WIDTH `else 128 `endif;
`AXI_DATA_WIDTH`, or `AXI_DWIDTH`? `AXI_WIDTH` is very ambiguous, when talking AXI.

2022-01-28 08:28 UTC, suehtamacv commented on hardware/src/mempool_pkg.sv
> +  localparam integer unsigned NumAXIMastersPerGroup = 1;
Parameter in `config.mk`?

2022-01-28 15:14 UTC, SamuelRiedel commented on hardware/deps/snitch/src/snitch_icache/snitch_icache.sv
> -        .data_o  ( extern_rsp_q    )
Yes, there is now an explicit AXI cut in the tile. These changes are mainly to be aligned with upstream, as they removed those spill registers.

2022-01-28 15:23 UTC, SamuelRiedel commented on hardware/src/axi_hier_interco.sv
> +  end else if (Radix <= 1) begin : gen_error
It would also work yes, but I prefer having the differentiation between the radix or the number of ports being the problem. We could move it to the beginning, but radix==1 is no problem if the bypass condition is met, so just to make life a bit easier, I put it here.

2022-01-28 15:27 UTC, SamuelRiedel commented on hardware/src/axi_hier_interco.sv
> +    end
Done.

2022-01-28 15:28 UTC, SamuelRiedel commented on hardware/src/axi_hier_interco.sv
> +        .SetCount     (2           ),
They are a reasonable choice considering the size of our instruction caches. But they can of course be changed.

2022-01-28 15:30 UTC, SamuelRiedel commented on hardware/src/ctrl_registers.sv
> +  // [59:56]:ro_cache_end_3                 (rw)
That is a reasonable number of regions we might need. One for instructions, one for read-only data, and two 'spare' ones for loading in data like matrices for example.

2022-01-28 15:54 UTC, SamuelRiedel commented on hardware/src/axi_hier_interco.sv
> +        .SetCount     (2           ),
I made this a bit easier to configure through the package.

2022-01-28 15:57 UTC, SamuelRiedel commented on hardware/src/mempool_pkg.sv
> +  localparam integer unsigned AxiDataWidth     = `ifdef AXI_WIDTH `AXI_WIDTH `else 128 `endif;
Good point, I like `AXI_DATA_WIDTH`

2022-01-30 15:07 UTC, suehtamacv approved these changes
LGTM! :tada: Let me know the result of the BE trials.

2022-01-31 15:41 UTC, merged