Performance metrics
pulp-platform/mempool pull request #89
Opened 2023-10-09 12:10 UTC by SamuelRiedel

Disable the simulation-only debugging CSRs (tracing, stack-overflow warning) and parameterize the stall counter performance registers.

## Changelog

### Changed
- Parametrize the performance counters

### Fixed
- Properly disable the debugging CSRs in ASIC implementations

## Checklist

- [ ] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

2023-10-11 06:19 UTC, mbertuletti requested changes
The PR looks good to me. With little effort we can adapt it to the TeraPool and the MinPool configs.

2023-10-11 06:19 UTC, mbertuletti commented on hardware/scripts/questa/wave.tcl
As you have the maximum set to the number of cores this would just work for MemPool right? Could we have a branch that checks on the configuration and selects the maximum range accordingly?

2023-10-11 06:19 UTC, mbertuletti commented on hardware/tb/mempool_tb.sv
If you declare your counters as "real" and you normalize by the number of cores we can have a configuration independent profile that gives a self-explanatory metric between 0 and 1.

2023-10-11 08:58 UTC, sermazz commented on hardware/tb/mempool_tb.sv
That's a cool idea but I would not abstract stuff too much in the waveforms, I think I would prefer to see the raw number of MACs per cycle for example. I would rather address your other comment about the maximum in the waveforms tcl.

2023-10-11 09:02 UTC, sermazz commented on hardware/scripts/questa/wave.tcl
Really makes sense, should also be very quick.
You just need, e.g. `set num_cores [expr [examine -radix dec mempool_pkg::NumCores]` and then use `$num_cores` instead of `256.0` :)

2023-10-11 09:04 UTC, sermazz commented
Lgtm, after we resolve Marco's comment!

2023-10-11 09:06 UTC, sermazz reviewed
Lgtm, after we resolve [Marco's comment](https://github.com/pulp-platform/mempool/pull/89/files#r1354151091)!

2023-10-11 13:49 UTC, SamuelRiedel commented on hardware/scripts/questa/wave.tcl
Of course, I fixed it accordingly.

2023-10-11 13:52 UTC, SamuelRiedel commented on hardware/tb/mempool_tb.sv
I agree with Sergio here. I was also considering doing the metrics in percentages, but for debugging, it is more valuable to me personally to see exactly how many cores are doing what. Does that also work for you? Alternatively, we can also have both. :)

2023-10-12 15:03 UTC, mbertuletti approved these changes
The changes are okay, when the CI passes we can merge.

2023-10-12 15:10 UTC, merged