Software restructuring
pulp-platform/mempool pull request #96
Opened 2024-02-23 13:30 UTC by SamuelRiedel

Start the software restructuring by moving the kernels, data, and tests to dedicated folders. Additionally, the kernel header files are renamed to follow a naming convention.

Changes not included:
- The systolic kernels are left mainly untouched since we have a major update on the systolic update in the pipeline.
- The integer matmul kernels & applications will be cleaned up in a later PR.
- The data generation framework will be overhauled in a later PR.
- This PR only moves files and does not clean up the code inside or rename the functions. We can do this in a second step.

## Changelog

### Changed
- Restructure the software folder by moving kernels, data, and tests to dedicated folders

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

2024-03-11 11:10 UTC, sermazz requested changes
To summarize what we have discussed, we currently have directories with different "meanings" at the same level of hierarchy. So I would make the structure more straightforward by having something like:

```
+ apps
   > bare_metal
   > omp
   > halide
+ kernels
   > bare_metal
   > omp
   > halide
+ runtime
   > omp
   > halide
and so on..
```

For the systolic apps and kernels, we can leave them as they are in this merge request. Once merged, I will rebase and fix them myself according to the new structure.
For the data generation framework, it would be nice to have a single scrip taking in `data.args` the dimensions of the matrices to generate and the model (matmul, conv2d, FFT, ...) to generate the golden output; currently some scripts are in `/mempool/scripts` and some in `/mempool/software/data`. I can help with that.

2024-03-14 13:26 UTC, sermazz approved these changes

2024-03-14 13:27 UTC, mbertuletti approved these changes
This works for me, can be merged.
Just a minor: is it wanted that the riscv-tests run on MemPool config by default?

2024-03-14 13:32 UTC, merged

2024-03-14 13:33 UTC, SamuelRiedel commented
> This works for me, can be merged. Just a minor: is it wanted that the riscv-tests run on MemPool config by default?

The CI runs them on MinPool as far as I can see. If you run them yourself, I don't think we specify a config.